name: Trigger-Jenkins

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on:
      - self-hosted
      - linux

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Jenkins Job
        run: |
          curl -X POST \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB }}/build"
